on:
  push:
    branches:
      - master
      - deployment/ecr-configuration

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: defi-explorer-bitcore-node
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker --version
          docker build  --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new image ID in the Amazon ECS task definition for Bitcore node
        id: bitcore-node-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./.github/workflows/explorer-bitcore-node-mainnet-task.json
          container-name: bitcore-node-mainnet
          image: ${{ steps.build-image.outputs.image }}

      - name: Fill in the new image ID in the Amazon ECS task definition for Insight
        id: insight-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./.github/workflows/explorer-insight-mainnet-task.json
          container-name: insight-mainnet
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Bitcore node on ECS task definition for mainnet
        id: ecs-deploy-bitcore-node
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.bitcore-node-task-def.outputs.task-definition }}
          service: explorer-bitcore-node-mainnet-service
          cluster: defi-explorer-mainnet
          wait-for-service-stability: true

      - name: Deploy Insight on ECS task definition for mainnet
        id: ecs-deploy-insight
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.insight-task-def.outputs.task-definition }}
          service: explorer-insight-mainnet-service
          cluster: defi-explorer-mainnet
          wait-for-service-stability: true
